# Generated by Django 5.2 on 2025-05-05 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique department identifier (e.g. CSE, ECE)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Department code must be uppercase letters only', regex='^[A-Z]{2,10}$')], verbose_name='Department Code')),
                ('name', models.CharField(help_text='Official department name', max_length=100, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='departments_code_35a421_idx'), models.Index(fields=['is_active'], name='departments_is_acti_51d68f_idx')],
            },
        ),
    ]
